### ISSUE TITLE
How do I define a piece of HTML as safe?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch-angular-app#11]
In the [controller.js](https://github.com/fergiemcdowall/norch-angular-app/blob/master/app/js/controllers.js#L77-L79) there is a little function to define some HTML string as safe. How do I get to use it in my template [search-list.html](https://github.com/fergiemcdowall/norch-angular-app/blob/master/app/partials/search-list.html)?

I have a teaser field that I want to render.

**Comment by eklem** [comment]
Ok, figured it out:

``` html
<blockquote ng-bind-html="trustworthy(item.document.teaser)"></blockquote>
```

**Comment by fergiemcdowall** [comment]
Goody! :)
