### ISSUE TITLE
cross-origin request blocked on firefox browser

### ISSUE THREAD

**Issue by larsvoigt** [fergiemcdowall/norch-angular-app#3]
I have cloned your example app und ran it.  It starts fine in Firefox, but then if I begin to type a word nothing is happens. No suggestions. I`m looking into browser console and see the issue. The result of my search request is received but the browser makes a cross-origin request block and the data can't be processed. 
What goes wrong? 

I  would like to use norch in the same scenario at my application. 
How can I make a request from a different application to the norch server? 

Thanks for helping me.

Lars

**Comment by fergiemcdowall** [comment]
Try starting Norch (not the app, but the actual server) with the (new and undocumented) `-c` option:

If you type in `norch -h` you will see how to use it

**Comment by fergiemcdowall** [comment]
And yes, I really should update the docs! :smile:

**Comment by larsvoigt** [comment]
You made my day! Thanks a lot. It works! Norch rocks :-)

**Comment by fergiemcdowall** [comment]
:+1: :smiley:
