### ISSUE TITLE
Help the newbies with a bit more explanation on installing?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch-angular-app#6]
Could it be an idea to explain that you clone the code

``` console
git clone git@github.com:fergiemcdowall/norch-angular-app.git
```

and that you need to change directory

``` console
cd norch-angular-app
```

before you do

``` console
npm install
...
npm start
```

I figured it out, but the threshold for testing will be much lower if this is explained. I'll add it if you think it's a good idea, and you'll give me edit access to the procjet.

**Comment by fergiemcdowall** [comment]
Yes, please update the docs to make them more sensible! :)
